### ISSUE TITLE
Azure SSO is working

### ISSUE THREAD

**Issue by platipusica** [SAML-Toolkits/python3-saml#179]
Continuing on #96 

I can report that MS Azure SSO is working with this settings.json for demo-flask:

```
.
.
    "idp": {
        "entityId": "https://sts.windows.net/1ce6feb6-98e1-4ad4-a83d-20d513bc103d/",
        "singleSignOnService": {
            "url": "https://login.microsoftonline.com/1ce6feb6-98e1-4ad4-a83d-20d513bc103d/saml2",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "singleLogoutService": {
            "url": "https://login.microsoftonline.com/common/wsfederation?wa=wsignout1.0",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
        },
.
.
```
This is with flask installed with pip:
Flask 0.12.2
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609]

With flask installed with pip and:
Python 3.7.4
Flask 1.1.1
Werkzeug 1.0.0

doesn't work.

**Comment by pitbulk** [comment]
What error do you get?

**Comment by platipusica** [comment]
This is the error:

source ~/Downloads/SAML/py37/bin/activate
(py37) d@venus ~/Downloads/SAML/python3-saml-master/demo-flask_old/demo-flask $ python index.py
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 211-880-796
127.0.0.1 - - [11/Feb/2020 10:49:07] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Downloads/SAML/py37/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Downloads/SAML/py37/lib/python3.7/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Downloads/SAML/python3-saml-master/demo-flask_old/demo-flask/index.py", line 41, in index
    auth = init_saml_auth(req)
  File "/Downloads/SAML/python3-saml-master/demo-flask_old/demo-flask/index.py", line 18, in init_saml_auth
    auth = OneLogin_Saml2_Auth(req, custom_base_path=app.config['SAML_PATH'])
  File "/Downloads/SAML/py37/lib/python3.7/site-packages/onelogin/saml2/auth.py", line 54, in __init__
    self.__settings = OneLogin_Saml2_Settings(old_settings, custom_base_path)
  File "/Downloads/SAML/py37/lib/python3.7/site-packages/onelogin/saml2/settings.py", line 107, in __init__
    ','.join(self.__errors)
onelogin.saml2.errors.OneLogin_Saml2_Error: Invalid dict settings at the file: sp_attributeConsumingService_requestedAttributes_name_invalid
127.0.0.1 - - [11/Feb/2020 10:49:07] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Feb/2020 10:49:07] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Feb/2020 10:49:07] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Feb/2020 10:49:07] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [11/Feb/2020 10:49:08] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -

**Comment by platipusica** [comment]
No luck:

```
demo-flask $ pip install flask==1.0
Collecting flask==1.0
  Downloading https://files.pythonhosted.org/packages/55/b1/4365193655df97227ace49311365cc296e74b60c7f5c63d23cd30175e2f6/Flask-1.0-py2.py3-none-any.whl (97kB)
     |████████████████████████████████| 102kB 5.2MB/s 
Requirement already satisfied: Werkzeug>=0.14 in /home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages (from flask==1.0) (1.0.0)
Requirement already satisfied: Jinja2>=2.10 in /home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages (from flask==1.0) (2.11.1)
Requirement already satisfied: click>=5.1 in /home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages (from flask==1.0) (7.0)
Requirement already satisfied: itsdangerous>=0.24 in /home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages (from flask==1.0) (1.1.0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages (from Jinja2>=2.10->flask==1.0) (1.1.1)
Installing collected packages: flask
  Found existing installation: Flask 0.10.1
    Uninstalling Flask-0.10.1:
      Successfully uninstalled Flask-0.10.1
Successfully installed flask-1.0
WARNING: You are using pip version 19.3.1; however, version 20.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
(py37) dbabic@venus ~/Downloads/SAML/python3-saml-master_py37/python3-saml-master/demo-flask $ python3.7 index.py 
 * Serving Flask app "index" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:8000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 289-747-666
^C(py37) dbabic@venus ~/Downloads/SAML/python3-saml-master_py37/python3-saml-masr/demo-flask $ vi index.py 
(py37) dbabic@venus ~/Downloads/SAML/python3-saml-master_py37/python3-saml-master/demo-flask $ python3.7 index.py 
 * Serving Flask app "index" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://0.0.0.0:5000/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 289-747-666
127.0.0.1 - - [11/Feb/2020 13:56:36] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 2301, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 2287, in wsgi_app
    response = self.handle_exception(e)
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1733, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dbabic/Downloads/SAML/python3-saml-master_py37/python3-saml-master/demo-flask/index.py", line 40, in index
    auth = init_saml_auth(req)
  File "/home/dbabic/Downloads/SAML/python3-saml-master_py37/python3-saml-master/demo-flask/index.py", line 18, in init_saml_auth
    auth = OneLogin_Saml2_Auth(req, custom_base_path=app.config['SAML_PATH'])
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/onelogin/saml2/auth.py", line 54, in __init__
    self.__settings = OneLogin_Saml2_Settings(old_settings, custom_base_path)
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/onelogin/saml2/settings.py", line 107, in __init__
    ','.join(self.__errors)
onelogin.saml2.errors.OneLogin_Saml2_Error: Invalid dict settings at the file: sp_acs_url_invalid,sp_sls_url_invalid
127.0.0.1 - - [11/Feb/2020 13:56:37] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Feb/2020 13:56:37] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Feb/2020 13:56:37] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Feb/2020 13:56:37] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
127.0.0.1 - - [11/Feb/2020 13:56:40] "GET / HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 2301, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 2287, in wsgi_app
    response = self.handle_exception(e)
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1733, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/flask/app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/dbabic/Downloads/SAML/python3-saml-master_py37/python3-saml-master/demo-flask/index.py", line 40, in index
    auth = init_saml_auth(req)
  File "/home/dbabic/Downloads/SAML/python3-saml-master_py37/python3-saml-master/demo-flask/index.py", line 18, in init_saml_auth
    auth = OneLogin_Saml2_Auth(req, custom_base_path=app.config['SAML_PATH'])
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/onelogin/saml2/auth.py", line 54, in __init__
    self.__settings = OneLogin_Saml2_Settings(old_settings, custom_base_path)
  File "/home/dbabic/Downloads/SAML/py37/lib/python3.7/site-packages/onelogin/saml2/settings.py", line 107, in __init__
    ','.join(self.__errors)
onelogin.saml2.errors.OneLogin_Saml2_Error: Invalid dict settings at the file: sp_acs_url_invalid,sp_sls_url_invalid
127.0.0.1 - - [11/Feb/2020 13:56:40] "GET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1" 200 -
127.0.0.1 - - [11/Feb/2020 13:56:40] "GET /?__debugger__=yes&cmd=resource&f=jquery.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Feb/2020 13:56:40] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
127.0.0.1 - - [11/Feb/2020 13:56:40] "GET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 200 -
```

**Comment by platipusica** [comment]
Tried Python 6 as well. No luck with flask demo even tho all tests went well:

flask --version
Flask 1.0
Python 3.6.0 (default, Feb 11 2020, 14:05:54) 
[GCC 5.4.0 20160609]

Installed python3-saml - no go.
Installed with python setup.py install from master.zip - no go.

python setup.py test
.
.
----------------------------------------------------------------------
Ran 243 tests in 249.613s

OK

**Comment by platipusica** [comment]
Hmm, 

in DOCo it says: "The Onelogin's Python Toolkit allows you to provide the settings info in 2 ways: Settings files or define a setting dict. In the demo-flask, it uses the first method."
```
.
.

File "/Downloads/SAML/py36/lib/python3.6/site-packages/python3_saml-1.9.0-py3.6.egg/onelogin/saml2/settings.py", line 107, in __init__
    ','.join(self.__errors)
onelogin.saml2.errors.OneLogin_Saml2_Error: **Invalid dict settings at the file**: sp_acs_url_invalid,sp_sls_url_invalid
```

**Comment by platipusica** [comment]
Solved.

**Comment by platipusica** [comment]
Nginx,
Gunicorn,
Python 3.7.4,
python3-saml from pip:

```
------------- -------
Click         7.0    
cssselect     1.1.0  
defusedxml    0.6.0  
Flask         1.0    
gunicorn      20.0.4 
isodate       0.6.0  
itsdangerous  1.1.0  
jam.py        5.4.87 
Jinja2        2.11.1 
lxml          4.5.0  
MarkupSafe    1.1.1  
parse         1.14.0 
parsel        1.5.2  
parso         0.6.1  
pip           19.3.1 
pkg-resources 0.0.0  
pkgconfig     1.5.1  
psycopg2      2.8.4  
pycparser     2.19   
pyjsparser    2.7.1  
pyparsing     2.4.6  
python3-saml  1.9.0  
setuptools    45.1.0 
six           1.14.0 
urllib3       1.25.8 
w3lib         1.21.0 
Werkzeug      1.0.0  
wheel         0.33.6 
xmlsec        1.3.3 
```
![Screenshot from 2020-02-12 12-04-21](https://user-images.githubusercontent.com/9026100/74302193-8ded7400-4d90-11ea-9b13-7e708abd3ebd.png)

**Comment by platipusica** [comment]
I will try to document the steps for Azure SSO in here.

First we need Azure Active Directory and New Enterprise Application. 
Go for Single Sign-On with SAML.

Name the Entity ID as the site we are accessing and Reply URL (Assertion ) as your site/?acs (this is from demo-flask saml/settings.json file).

Leave everything else as per Azure defaults.

![Screenshot from 2020-02-12 12-28-30](https://user-images.githubusercontent.com/9026100/74303127-b3c84800-4d93-11ea-877f-71879e731a83.png)

You can now add your "Users and groups" 

Now the tricky part...

**Comment by platipusica** [comment]
Install python3-saml with pip in virtual env.

Download zip repo from https://github.com/onelogin/python3-saml, and unzip content.

Navigate to demo-flask folder and update saml/settings.json with our SP and AZURE details from above:
"Login URL" is singleSignOnService for python3-saml
"Azure AD Identifier" is entityId for python3-saml
"Logout URL" is singleLogoutService for python3-saml

x509cert is our SAML cert in one single line.

```
cat saml/settings.json 
{
    "strict": true,
    "debug": true,
    "sp": {
        "entityId": "https://venus01.YOUR_DOMAIN",
        "assertionConsumerService": {
            "url": "https://venus01.YOUR_DOMAIN/?acs",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-POST"
        },
        "singleLogoutService": {
            "url": "https://venus01.YOUR_DOMAIN/?sls",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "NameIDFormat": "urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified",
        "x509cert": "",
        "privateKey": ""
    },
    "idp": {
        "entityId": "https://sts.windows.net/1ce6feb6..../",
        "singleSignOnService": {
            "url": "https://login.microsoftonline.com/1ce6feb6...../saml2",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "singleLogoutService": {
            "url": "https://login.microsoftonline.com/common/wsfederation?wa=wsignout1.0",
            "binding": "urn:oasis:names:tc:SAML:2.0:bindings:HTTP-Redirect"
        },
        "x509cert": "your_cert_in_one_sigle_line"
    }
}
```

**Comment by platipusica** [comment]
Nginx config file:

```
server {
        listen 443 default_server;

        server_name venus01.YOUR_DOMAIN;

        access_log off;

        ssl on;
        ssl_certificate /etc/nginx/ssl/venus01.YOUR_DOMAIN.crt;
        ssl_certificate_key /etc/nginx/ssl/venus01.YOUR_DOMAIN.key;
        add_header Strict-Transport-Security "max-age=31536000";

        location / {
            try_files $uri @wsgi;
        }
        location @wsgi {
            proxy_pass http://unix:/tmp/gunicorn.sock;
            include proxy_params;
        }

}
```

**That is it!**

**Comment by peralisairam** [comment]
use 'lowercase_urlencoding': True, for both azure ad and adfs in index.py and strict to false in settings.json if application is behind proxy. just suggesting if it would be of help to anyone.

**Comment by pitbulk** [comment]
strict=false should not be used for production environment. Better to set properly the request and settings
