### ISSUE TITLE
It does not redirect to the page of the SP with active session.

### ISSUE THREAD

**Issue by omunozn** [SAML-Toolkits/python3-saml#244]
Hi there,

After updating my system to version 3.1 of Django, which implements an IDP, I started having problems. Precisely, the flow is as follows:

A user authenticates to my IDP, and is then redirected to the SP correctly.
After this, the user tries to re-authenticate from the SP, already having an active session, and I get the following error, which I see from the SP:

> Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 47, in inner
  response = get_response(request)
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 179, in _get_response
  response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
  return view_func(*args, **kwargs)
File "/usr/development/app/auth_coesys/views.py", line 101, in acs_id_uruguay
  return coesys.acs_id_uruguay()
File "/usr/development/app/auth_coesys/auth.py", line 280, in acs_id_uruguay
  self.__auth.process_response()
File "/usr/local/lib/python3.6/site-packages/onelogin/saml2/auth.py", line 105, in process_response
  response = OneLogin_Saml2_Response(self.__settings, self.__request_data['post_data']['SAMLResponse'])
File "/usr/local/lib/python3.6/site-packages/onelogin/saml2/response.py", line 39, in __init__
  self.document = OneLogin_Saml2_XML.to_etree(self.response)
File "/usr/local/lib/python3.6/site-packages/onelogin/saml2/xml_utils.py", line 66, in to_etree
  return OneLogin_Saml2_XML._parse_etree(xml, forbid_dtd=True)
File "/usr/local/lib/python3.6/site-packages/defusedxml/lxml.py", line 145, in fromstring
  rootelement = _etree.fromstring(text, parser, base_url=base_url)
File "src/lxml/etree.pyx", line 3237, in lxml.etree.fromstring
File "src/lxml/parser.pxi", line 1896, in lxml.etree._parseMemoryDocument
File "src/lxml/parser.pxi", line 1784, in lxml.etree._parseDoc
File "src/lxml/parser.pxi", line 1141, in lxml.etree._BaseParser._parseDoc
File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1

When I compare the version that works (with Django 1.11) with the current version of Django, I notice that there is a difference in the format in which the SAMLResponse is sent from the browser to the SP, after my IDP sends the browser the SAMLResponse , since when I do it with the version of Django 1.11 it is sent as follows:`SAMLResponse: PHNhbWwycDpSZXNwb ... ==`, on the other hand when I do it with version 3.1 of Django, it does it with the following format: `SAMLResponse: b'PHNhbWwycDpSZXNwb ... == '`. From my IDP I always send the SAMLResponse with the same format, both in version 3.1 and in 1.11.

Also, in both versions of Django, when a user authenticates for the first time, without an active session, the format of the SAMLResponse that is sent, from the browser to the SP, is the same, being the following: `SAMLResponse: PHNhbWwycDpSZXNwb ... ==`

The questions are:

**Question 1:** Is there any configuration within the library to be added when updating Django to version 3.1?

**Question 2:** Do you plan to upload a demo for version 3.1 of Django?

The version I use of `python3-saml` is 1.9.0.

Thanks!

**Comment by pitbulk** [comment]
I have no tested python3-saml with Django

I believe the issue is related in [how the POST info is provided to the saml toolkit](https://github.com/onelogin/python3-saml/blob/master/demo-django/demo/views.py#L27)
```
'post_data': request.POST.copy()
```

Maybe is related with what is explained [here](https://stackoverflow.com/questions/29514077/get-request-body-as-string-in-django) and you need to provide 

Maybe take a look at: https://github.com/penn-state-dance-marathon/python3-saml-django

I have no plans to upgrade the Django demo, but PRs from the community are welcome
