### ISSUE TITLE
ImportError: lxml.etree does not export expected C function adoptExternalDocument

### ISSUE THREAD

**Issue by huangsam** [SAML-Toolkits/python3-saml#82]
Encountered this issue when running this library within a Linux environment/container ([`python:3.6-slim`](https://github.com/docker-library/python/blob/a4ce69de053337ec22d7f322cd997398eeba2350/3.6/stretch/slim/Dockerfile)):

```python
app_1  | + python3 manage.py migrate
app_1  | Traceback (most recent call last):
app_1  |   File "manage.py", line 22, in <module>
app_1  |     execute_from_command_line(sys.argv)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
app_1  |     utility.execute()
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/__init__.py", line 355, in execute
app_1  |     self.fetch_command(subcommand).run_from_argv(self.argv)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
app_1  |     self.execute(*args, **cmd_options)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 327, in execute
app_1  |     self.check()
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 359, in check
app_1  |     include_deployment_checks=include_deployment_checks,
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 62, in _run_checks
app_1  |     issues.extend(super(Command, self)._run_checks(**kwargs))
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/management/base.py", line 346, in _run_checks
app_1  |     return checks.run_checks(**kwargs)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/registry.py", line 81, in run_checks
app_1  |     new_errors = check(app_configs=app_configs)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 16, in check_url_config
app_1  |     return check_resolver(resolver)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/core/checks/urls.py", line 26, in check_resolver
app_1  |     return check_method()
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 254, in check
app_1  |     for pattern in self.url_patterns:
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
app_1  |     res = instance.__dict__[self.name] = self.func(instance)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 405, in url_patterns
app_1  |     patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/utils/functional.py", line 35, in __get__
app_1  |     res = instance.__dict__[self.name] = self.func(instance)
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/urls/resolvers.py", line 398, in urlconf_module
app_1  |     return import_module(self.urlconf_name)
app_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
app_1  |     return _bootstrap._gcd_import(name[level:], package, level)
app_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
app_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
app_1  |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
app_1  |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
app_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
app_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
app_1  |   File "/app/customer_success_site/urls.py", line 23, in <module>
app_1  |     url(r'', include('tools.urls')),
app_1  |   File "/usr/local/lib/python3.6/site-packages/django/conf/urls/__init__.py", line 50, in include
app_1  |     urlconf_module = import_module(urlconf_module)
app_1  |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
app_1  |     return _bootstrap._gcd_import(name[level:], package, level)
app_1  |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
app_1  |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
app_1  |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
app_1  |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
app_1  |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
app_1  |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
app_1  |   File "/app/tools/urls.py", line 2, in <module>
app_1  |     from . import views
app_1  |   File "/app/tools/views.py", line 19, in <module>
app_1  |     from .saml import init_saml_auth, prepare_django_request
app_1  |   File "/app/tools/saml.py", line 4, in <module>
app_1  |     from onelogin.saml2.auth import OneLogin_Saml2_Auth
app_1  |   File "/usr/local/lib/python3.6/site-packages/onelogin/saml2/auth.py", line 14, in <module>
app_1  |     import xmlsec
app_1  | ImportError: lxml.etree does not export expected C function adoptExternalDocument
```

Not sure what's the issue here, but noticed that it uninstalled `lxml 4.1.1` when I tried `pip install`:

```python
Installing collected packages: beautifulsoup4, pytz, Django, gunicorn, htmlmin, lxml, mysqlclient, numpy, six, python-dateutil, pandas, psycopg2, rcssmin, requests, rjsmin, SQLAlchemy, xlrd, XlsxWriter, ujson, MarkupSafe, Jinja2, isodate, defusedxml, python3-saml
  Found existing installation: lxml 4.1.1
    Uninstalling lxml-4.1.1:
      Successfully uninstalled lxml-4.1.1
Successfully installed Django-1.11 Jinja2-2.9.6 MarkupSafe-1.0 SQLAlchemy-1.1.9 XlsxWriter-0.9.8 beautifulsoup4-4.6.0 defusedxml-0.5.0 gunicorn-19.7.1 htmlmin-0.1.10 isodate-0.6.0 lxml-3.7.3 mysqlclient-1.3.10 numpy-1.12.1 pandas-0.21.0 psycopg2-2.7.1 python-dateutil-2.6.0 python3-saml-1.3.0 pytz-2017.2 rcssmin-1.0.6 requests-2.14.2 rjsmin-1.0.12 six-1.10.0 ujson-1.35 xlrd-1.0.0
```

**Comment by phdd** [comment]
👍

**Comment by adu013** [comment]
Same issue here. Anybody please help

**Comment by RaidersII** [comment]
I think it's a dependencie's issue.
Python3-saml require 'xmlsec>=0.6.0' in its setup.py. And the version 0.6.0 of xmlsec require 'lxml >= 3.0' in its setup.py.
However the version 3.0 of lxml don't export `__pyx_capi__ = {'adoptExternalDocument': <capsule object "stru...`
This symbol was exported from the version 3.2.
So the solution was to upgrade lxml as @phdd said.
In my case I had an error with `TypeError: cleanup_namespaces() takes no keyword arguments` cleanup_namespaces takes keyword arguments from the 3.5 version of lxml
The updgrade of lxml fixed it
